src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 */
class Booking
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Livre::class, inversedBy="bookings")
     */
    private $livre;

    /**
     * @ORM\Column(type="date")
     */
    private $booking_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $return_date;

    /**
     * @ORM\Column(type="date")
     */
    private $expected_retrun_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $BackgroundColor;

    /**
     * @ORM\Column(type="boolean")
     */
    private $approver;



    

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getLivre(): ?Livre
    {
        return $this->livre;
    }

    public function setLivre(?Livre $livre): self
    {
        $this->livre = $livre;

        return $this;
    }

    public function getBookingDate(): ?\DateTimeInterface
    {
        return $this->booking_date;
    }

    public function setBookingDate(\DateTimeInterface $booking_date): self
    {
        $this->booking_date = $booking_date;

        return $this;
    }

    public function getReturnDate(): ?\DateTimeInterface
    {
        return $this->return_date;
    }

    public function setReturnDate(?\DateTimeInterface $return_date): self
    {
        $this->return_date = $return_date;

        return $this;
    }

    public function getExpectedRetrunDate(): ?\DateTimeInterface
    {
        return $this->expected_retrun_date;
    }

    public function setExpectedRetrunDate(\DateTimeInterface $expected_retrun_date): self
    {
        $this->expected_retrun_date = $expected_retrun_date;

        return $this;
    }

    public function getBackgroundColor(): ?string
    {
        return $this->BackgroundColor;
    }

    public function setBackgroundColor(string $BackgroundColor): self
    {
        $this->BackgroundColor = $BackgroundColor;

        return $this;
    }


    public function getApprover(): ?bool
    {
        return $this->approver;
    }

    public function setApprover(bool $approver): self
    {
        $this->approver = $approver;

        return $this;
    }
    public function getLivreTitle()
    {
        return $this->livre->getTitre();
    }
    public function getLivreId()
    {
        return $this->livre->getId();
    }


}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('booking_date',DateType::class,[
                'widget'=>'single_text',
            ])
            ->add('expected_retrun_date',DateType::class,[
                'widget'=>'single_text',
            ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Entity\Livre;
use App\Form\BookingType;
use App\Repository\BookingRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/booking')]
class BookingController extends AbstractController
{
    #[Route('/', name: 'booking_index', methods: ['GET'])]
    public function index(BookingRepository $bookingRepository): Response
    {
        return $this->render('booking/index.html.twig', [
            'bookings' => $bookingRepository->findAll(),
        ]);
    }

    #[Route('/{id}/new', name: 'booking_new', methods: ['GET','POST'])]
    public function new(Request $request,Livre $livre,BookingRepository $bookingRepository): Response
    {
        

        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid() ) {
            $entityManager = $this->getDoctrine()->getManager();

            $livre->retireDeQteStock();

            $booking->setBackgroundColor("green")
                    ->setApprover(false)
                    ->setLivre($livre)
                    ->setUser($this->getUser());

            $entityManager->persist($booking);
            $entityManager->flush();

            return $this->redirectToRoute('user_show', ['id'=>$this->getUser()], Response::HTTP_SEE_OTHER);
   
        }
        
        $events = $bookingRepository->findAll();
        $rdvs = [];

        foreach ($events as $event) {
            $rdvs[] = [
                'id' => $event->getId(),
                'start' => $event->getBookingDate()->format('Y-m-d'),
                'end' => $event->getExpectedRetrunDate()->format('Y-m-d'),
                'backgroundColor' => $event->getBackgroundColor(),
                'title' => $event->getLivreTitle(),
            ];
        }
        $data = json_encode($rdvs);

        return $this->renderForm('booking/new.html.twig', [
            'booking' => $booking,
            'form' => $form,
            'id'=>$livre,
            'data'=> $data
        ],);
    }

    #[Route('/{id}', name: 'booking_show', methods: ['GET'])]
    public function show(Booking $booking): Response
    {
        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
        ]);
    }

    #[Route('/{id}/edit', name: 'booking_edit', methods: ['GET','POST'])]
    public function edit(Request $request, Booking $booking): Response
    {
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('booking_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('booking/edit.html.twig', [
            'booking' => $booking,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'booking_delete', methods: ['POST'])]
    public function delete(Request $request, Booking $booking): Response
    {
        if ($this->isCsrfTokenValid('delete'.$booking->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($booking);
            $entityManager->flush();
        }

        return $this->redirectToRoute('booking_index', [], Response::HTTP_SEE_OTHER);
    }


}

templates/booking/_delete_form.html.twig
<form method="post" action="{{ path('booking_delete', {'id': booking.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ booking.id) }}">
    <button class="btn">Delete</button>
</form>

templates/booking/_form.html.twig
<div class="card-body">
{{ form_start(form) }}
    <div class="row mb-4">
      <div class="col">
        <label class="form-label" for="form3Example1">take date</label>
        <div class="form-outline">
          {{ form_widget(form.booking_date,{'attr':{'class' : 'form-control'}}) }}
          
        </div>
      </div>
      <div class="col">
        <label class="form-label" for="form3Example2">Retrun date</label>
        <div class="form-outline">
          {{ form_widget(form.expected_retrun_date,{'attr':{'class' : 'form-control'}}) }}
          
        </div>
      </div>
    </div> 
    <button type="submit" class="btn btn-primary">{{ button_label|default('Save') }}</button>
 {{ form_end(form) }}
</div>

templates/booking/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Booking{% endblock %}

{% block body %}
    <h1>Edit Booking</h1>

    {{ include('booking/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('booking_index') }}">back to list</a>

    {{ include('booking/_delete_form.html.twig') }}
{% endblock %}

templates/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Booking index{% endblock %}

{% block body %}
    <h1>Booking index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Booking_date</th>
                <th>Return_date</th>
                <th>Expected_retrun_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for booking in bookings %}
            <tr>
                <td>{{ booking.id }}</td>
                <td>{{ booking.bookingDate ? booking.bookingDate|date('Y-m-d') : '' }}</td>
                <td>{{ booking.returnDate ? booking.returnDate|date('Y-m-d') : '' }}</td>
                <td>{{ booking.expectedRetrunDate ? booking.expectedRetrunDate|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('booking_show', {'id': booking.id}) }}">show</a>
                    <a href="{{ path('booking_edit', {'id': booking.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('booking_new') }}">Create new</a>
{% endblock %}

templates/booking/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Booking{% endblock %}

{% block body %}
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
      <div class="container">
        <div class="card mb-8">
          <div class="card-body">
            {{ form_start(form) }}
              <div class="row mb-4">
                <div class="col">
                  <label class="form-label" for="form3Example1"><h2>take date</h2></label>
                  <div class="form-outline">
                    {{ form_widget(form.booking_date,{'attr':{'class' : 'form-control'}}) }}
                  </div>
                </div>
                <div class="col">
                  <label class="form-label" for="form3Example2"><h2>Retrun date</h2></label>
                  <div class="form-outline">
                    {{ form_widget(form.expected_retrun_date,{'attr':{'class' : 'form-control'}}) }}
                  </div>
                </div>
              </div> 
              <button type="submit" class="btn btn-primary">{{ button_label|default('Save') }}</button>
            {{ form_end(form) }}
          </div>
          <div class="card-body">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

{% block javascripts %}
<script>
    window.onload = () => {
        let calendarElt = document.querySelector("#calendrier")
        let calendar = new FullCalendar.Calendar(calendarElt, {
            initialView: 'dayGridMonth',
            headerToolbar: {
                start: 'prev,next today',
                center: 'title',
                end: 'dayGridMonth,timeGridWeek'
            },
            events : {{ data | raw}}
        })

        calendar.render()
    }
</script>

{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Booking{% endblock %}

{% block body %}
    <h1>Booking</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ booking.id }}</td>
            </tr>
            <tr>
                <th>Booking_date</th>
                <td>{{ booking.bookingDate ? booking.bookingDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Return_date</th>
                <td>{{ booking.returnDate ? booking.returnDate|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Expected_retrun_date</th>
                <td>{{ booking.expectedRetrunDate ? booking.expectedRetrunDate|date('Y-m-d') : '' }}</td>
            </tr>
           
        </tbody>
    </table>

    <a href="{{ path('booking_index') }}">back to list</a>

    <a href="{{ path('booking_edit', {'id': booking.id}) }}">edit</a>

    {{ include('booking/_delete_form.html.twig') }}
{% endblock %}