src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;


use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    const ROLE_ADMIN = "ROLE_ADMIN";

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\Length(min="8",minMessage="Votre mot de passe doit faire miminum 8 caracteres")
     * @Assert\EqualTo(propertyPath="comfirm_password", message="Vous n'avez pas tapé le meme mot de passe")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="user")
     */
    private $bookings;
    /** 
     * @Assert\EqualTo(propertyPath="password", message="Vous n'avez pas tapé le meme mot de passe")
     */
    public $comfirm_password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_naissance;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\OneToMany(targetEntity=Review::class, mappedBy="user")
     */
    private $reviews;



    public function __construct()
    {
        $this->bookings = new ArrayCollection();
        $this->reviews = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function isAdmin(): bool
    {
        return in_array(self::ROLE_ADMIN, $this->getRoles());
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setUser($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getUser() === $this) {
                $booking->setUser(null);
            }
        }

        return $this;
    }

    public function getrole()
    {
        $roles="";
        foreach ($this->getRoles() as $role) {
            if($role == self::ROLE_ADMIN){
                $roles .= "Admin "; ; 
            }
            if($role == 'ROLE_USER'){
                $roles .= "User "; ; 
            }
        }
        return  $roles;
    }

    public function getLanguage(): ?string
    {
        return $this->language;
    }

    public function setLanguage(string $language): self
    {
        $this->language = $language;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function __toString()
    {
        return $this->id." - ".$this->nom." ".$this->prenom;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * @return Collection|Review[]
     */
    public function getReviews(): Collection
    {
        return $this->reviews;
    }

    public function addReview(Review $review): self
    {
        if (!$this->reviews->contains($review)) {
            $this->reviews[] = $review;
            $review->setUser($this);
        }

        return $this;
    }

    public function removeReview(Review $review): self
    {
        if ($this->reviews->removeElement($review)) {
            // set the owning side to null (unless already changed)
            if ($review->getUser() === $this) {
                $review->setUser(null);
            }
        }

        return $this;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Entity\User;
use App\Form\EditeUserType;
use App\Form\UserType;
use App\Repository\BookingRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'user_new', methods: ['GET','POST'])]
    public function new(Request $request): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'user_show', methods: ['GET'])]
    public function show(User $user,BookingRepository $bookingRepository): Response
    {
        $bookings = $bookingRepository->findBy(["user" => $user]);
        return $this->render('user/show.html.twig', [
            'user' => $user,
            'bookings'=> $bookings,
        ]);
    }

    #[Route('/{id}/edit', name: 'user_edit', methods: ['GET','POST'])]
    public function edit(Request $request, User $user): Response
    {

        $form = $this->createForm(EditeUserType::class, $user);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() /*&& $form->isValid()*/) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_show', ['id'=>$user], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete your profile?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn btn-outline-primary ms-1">Delete</button>
</form>

templates/user/_form.html.twig
<section style="background-color: #eee;">
    <div class="container py-5">
        <div class="row">
            <div class="col">
                <nav aria-label="breadcrumb" class="bg-light rounded-3 p-3 mb-4">
                  <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a href="#">Home</a></li>
                    <li class="breadcrumb-item"><a href="#">User</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Edit Profile</li>
                  </ol>
                </nav>
             </div>
        </div>

        <div class="row justify-content-md-center">
            <div class="col">
                <div class="card mb-4">
                    <div class="card-body">
                        {{ form_start(form) }}
                            <div class="row mb-4">
                              <div class="col">
                                <div class="form-outline">
                                  {{ form_widget(form.nom,{'attr':{'class' : 'form-control'}}) }}
                                  <label class="form-label" for="form3Example1">First name</label>
                                </div>
                              </div>
                              <div class="col">
                                <div class="form-outline">
                                  {{ form_widget(form.prenom,{'attr':{'class' : 'form-control'}}) }}
                                  <label class="form-label" for="form3Example2">Last name</label>
                                </div>
                              </div>
                            </div>                        
                            <div class="form-outline mb-4">
                             {{ form_widget(form.date_naissance,{'attr':{'class' : 'form-control'}}) }}
                              <label class="form-label" for="form3Example3">Birthday</label>
                            </div>                            
                            <div class="form-outline mb-4">
                               {{ form_widget(form.phone,{'attr':{'class' : 'form-control','type':'text'}}) }}
                              <label class="form-label" for="form3Example3">phone</label>
                            </div>


                           
                            
                            <button type="submit" class="btn btn-primary">{{ button_label|default('Save') }}</button>
                        {{ form_end(form) }}

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit User{% endblock %}

{% block body %}

    {{ include('user/_form.html.twig', {'button_label': 'Update'}) }}

{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block body %}
<section style="background-color: #eee;">
  <div class="container py-5">
    <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
              <h2 class="my-3"> {{ user.prenom}} {{ user.nom}}</h2>
              <h3 class="text-muted mb-4">{{user.email}}</h3>
            </div>
          </div>

        </div>
        <div class="col-lg-8">
            <div class="card mb-4">
              <div class="card-body">
                <div class="row">
                  <div class="col-sm-3">
                    <h3 class="mb-0">Full Name</h3>
                  </div>
                  <div class="col-sm-9">
                    <h3 class="text-muted mb-0">{{ user.prenom}} {{ user.nom}}</h3>
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-3">
                    <h3 class="mb-0">Email</h3>
                  </div>
                  <div class="col-sm-9">
                    <h3 class="text-muted mb-0">{{ user.email}}</h3>
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-3">
                    <h3 class="mb-0">Phone</h3>
                  </div>
                  <div class="col-sm-9">
                    <h3 class="text-muted mb-0">{{ user.phone}}</h3>
                  </div>
                </div>
                <hr>
                <div class="row">
                  <div class="col-sm-3">
                    <h3 class="mb-0">Birthday</h3>
                  </div>
                  <div class="col-sm-9">
                    <h3 class="text-muted mb-0">{{  user.dateNaissance ? user.dateNaissance|date('Y-m-d') : ''}}</h3>
                  </div>
                </div>
                <hr>
                
              </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card mb-4">
              <div class="card-body">
                <table class="table">
                    <thead>
                      <tr>
                        <th>livre</th>
                        <th>approver</th>
                        <th>recuperate book date </th>
                        <th>return date</th>
                        <th>expected retrun date</th>
                      </tr>
                    </thead>
                    <tbody>
                      {% for booking in bookings %}
                      <tr>
                        <th>{{booking.livre}}</th>
                        <th>{{booking.approver ? "approver" : "not approver"}}</th>
                        <td>{{booking.bookingdate|date('Y-m-d')}}</td>
                        <td>{{ booking.returndate ? booking.returndate|date('Y-m-d') : "not returned yet"}}</td>
                        <td>{{booking.expectedretrundate|date('Y-m-d')}}</td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
              </div>
            </div>
        </div>
        
    </div>
</div>
</section>

{% endblock %}